### ISSUE TITLE
Fontawesome instead of bs3 glyph

### ISSUE THREAD

**Issue by osv** [Meteor-Community-Packages/meteor-autoform#1271]
Hello, can we have support font-awesome instead hardcoded glyphicon? Glyphicons may be disables by some bs3 meteor packages.

templates/bootstrap3/components/afArrayField/afArrayField.html:

``` html
{{#if afArrayFieldHasMoreThanMinimum name=../atts.name minCount=../atts.minCount maxCount=../atts.maxCount}}
   <button type="button" class="btn btn-primary autoform-remove-item"><span class="glyphicon glyphicon-minus"></span></button>
{{/if}}
```

**Comment by rmuratov** [comment]
+1

**Comment by osv** [comment]
I don't make any hack, however, you can do it in various ways. Example, manually replace icon using onRendered. :)

```
Template.afArrayField_bootstrap3.onRender(function....
```

**Comment by rmuratov** [comment]
Yes, there are many options, thought may be there is some good wide used practise on it.

`onRendered` btw is not the best option, because some buttons are dynamically added.

I just defined required styles, it's enough for me:

```css
.glyphicon-plus:before {
  content: "\002b"; /*plus sign*/
}
.glyphicon-minus:before {
  content: "\2212"; /*minus sign*/
}
```
Thank you for answer anyway.
