### ISSUE TITLE
When customize array field in custom component, recieve an error `'lastIndexOf' of undefined`

### ISSUE THREAD

**Issue by alexandrzavalii** [Meteor-Community-Packages/meteor-autoform#1486]
The custom template is afArrayField_bootstrap3 with minor changes. I want to modify one field inside the array. 
When  I press add button, it displays error.

```
Exception in template helper: TypeError: Cannot read property 'lastIndexOf' of undefined
    at updateTrackedFieldValue 
```

Also the html tag doesn't have a name specified. It probably should be name="depots.0.placement.district"  
this are the changes that I made in template bootstrap3

```
<div class="autoform-array-item-body">
       {{#afEachArrayItem name=this.atts.name minCount=this.atts.minCount maxCount=this.atts.maxCount}}
                                <!-- causes error  -->
              {{> afQuickField name=this.current.placement.district label="district"}}
  {{/afEachArrayItem}}
 </div>
```

My simpleschema

```
@ssEshopDepot = new SimpleSchema(
  "depot_id":
    type: Number
    optional: true
  "depot_name":
    type: String
  "address":
    type: ssDepotAddress
  "placement":
    type: ssDepotPlacement
```

```
@ssDepotPlacement = new SimpleSchema(
  "county":
    type: String
  "city":
    type: String
    optional: true
  "district":
    type: String
    autoform:
      type: "select2"
)
```

My goal is to set options for select2 using helper.
