### ISSUE TITLE
Field type=Date loses value after validation fail.

### ISSUE THREAD

**Issue by Pierre-Ferreira** [Meteor-Community-Packages/meteor-autoform#917]
My autoForm field of type=Date loses its value when the form has a validation error on other fields. I have checked in the before and after hooks of the autoForm and RouteController and the value of that field is there the whole time, but it is not displayed in the field again.  

```
    startDate:
        type: Date
        label: 'Seit wann behandelst du?'
        optional: true
        custom: ->
            customCondition = this.field('treated').value == '1'
            if (customCondition && !this.isSet && (!this.operator || (this.value == null || this.value == "")))
         return "required"
        autoform:
            afFieldInput:
                placeholder: 'MM/JJJJ'
                type: "bootstrap-datepicker"
                datePickerOptions:
                    format: 'mm/yyyy'
                    minViewMode: 1
                    weekStart: 1
                    language: 'de'
```
